# FILE: analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - _archive/**
    - lib_backup/**
    - lib/features/brain/**
    - build/**
    - .dart_tool/**

linter:
  rules: